name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers with Wrangler
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: pnpm install
      - name: Build App
        run: pnpm run build
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
